codecov:
  require_ci_to_pass: no
  max_report_age: off

comment: false

ignore:
  - 'act/tests/*.py'
  - 'act/discovery/get_arm.py'
  - 'act/discovery/arm.py'
  - 'act/discovery/airnow.py'
  - 'act/discovery/asos.py'
  - 'act/discovery/cropscape.py'
  - 'act/discovery/neon.py'
  - 'act/discovery/noaapsl.py'
  - 'act/discovery/surfrad.py'
  - 'act/*version*py'
  - 'setup.py'
  - 'versioneer.py'

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 95
        threshold: 2%
        informational: true
    patch: off
    changes: off
