name: build-docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This job installs dependencies, build the website, and pushes it to `gh-pages`
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: docs/environment_docs.yml
          environment-name: act-docs
          cache-downloads: true

      - name: Fetch all history for all tags and branches
        run: |
           git fetch --prune --unshallow

      - name: Install ACT
        run: |
          pip install -e . --no-deps --force-reinstall
      # Build the website
      - name: Build the site
        run: |
          cd docs
          make html
        env:
          ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
          ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
          AIRNOW_API: ${{ secrets.AIRNOW_API }}
      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          cname: https://arm-doe.github.io/ACT/
