name: Python Package using Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COVERALLS_TOKEN: ${{ secrets.COVERLALLS_REPO_TOKEN }}

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.python-version }}
    if: github.repository == 'ARM-DOE/ACT'
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [macOS, ubuntu, Windows]
        inlcude:
          - os: macos-latest
            PLAT: arm64
            INTERFACE64: ""
            platform: [x64]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: ./continuous_integration/environment_actions.yml
          activate-environment: act_env
          auto-activate-base: False
          mamba-version: '*'
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Install ACT
        run: |
          python -m pip install -e .

      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          # Switching back to original flake
          python -m flake8 --max-line-length=127 --ignore=F401,E402,W504,W605,F403
      - name: Test with pytest
        run: |
          conda install pytest
          conda install pytest-cov
          conda install pytest-mpl
          python -m pytest --mpl --cov=act/ --cov-config=.coveragerc

      - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Test

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true